###
### A complete description of a Prefect Deployment for flow 'MNIST Traning Flow Prefect-AKS-MLFlow'
###
name: mnist-prefect-aks-mlflow-adls
description: null
version: 9561be27faab70b53383152db94cce44
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: kubernetes
tags: []
parameters: {}
schedule: null
is_schedule_active: true
infra_overrides:
  env.EXTRA_PIP_PACKAGES: adlfs torch torchvision keras mlflow tensorflow azure-cli
    azure-identity==1.12.0 azure-storage-blob==12.14.1
infrastructure:
  type: kubernetes-job
  env: {}
  labels: {}
  name: null
  command: null
  image: prefecthq/prefect:2.8.4-python3.8
  namespace: prefect-cloud
  service_account_name: null
  image_pull_policy: null
  cluster_config: null
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels: {}
    spec:
      template:
        spec:
          parallelism: 1
          completions: 1
          restartPolicy: Never
          containers:
          - name: prefect-job
            env: []
  customizations: []
  job_watch_timeout_seconds: null
  pod_watch_timeout_seconds: 60
  stream_output: true
  finished_job_ttl: null
  block_type_slug: kubernetes-job
  _block_type_slug: kubernetes-job

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: MNIST Traning Flow Prefect-AKS-MLFlow
manifest_path: null
storage:
  bucket_path: prefectblock
  azure_storage_connection_string: '**********'
  azure_storage_account_name: null
  azure_storage_account_key: null
  azure_storage_tenant_id: null
  azure_storage_client_id: null
  azure_storage_client_secret: null
  azure_storage_anon: true
  _block_document_id: b65a5500-8220-4da4-996d-7f5c1632ff11
  _block_document_name: adlsgen2storage01
  _is_anonymous: false
  block_type_slug: azure
  _block_type_slug: azure
path: ''
entrypoint: Train-MLFlow-Prefect.py:train_mnist
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
timestamp: '2023-03-15T18:33:44.909860+00:00'
